name: .NET Core

on:
  push:
    branches: [ master, bakx-patch-1 ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Build SP Core
      run: dotnet build "SP.Core/SP.Core/SP.Core.csproj" /t:Restore,Clean,Rebuild /p:Configuration="Release" /p:Platform="Any CPU" /p:SourceRevisionId="${{ github.sha }}"
    - name: Build Plugins.Api.Https
      run: dotnet build "SP.Core/Plugins/Api/Api.Https/Plugins.Api.Https.csproj" /t:Restore,Clean,Rebuild /p:Configuration="Release" /p:Platform="Any CPU" /p:SourceRevisionId="${{ github.sha }}"
    - name: Build Plugins.Api.gRPC
      run: dotnet build "SP.Core/Plugins/Api/Api.GRPC/Plugins.Api.gRPC.csproj" /t:Restore,Clean,Rebuild /p:Configuration="Release" /p:Platform="Any CPU" /p:SourceRevisionId="${{ github.sha }}"
    - name: Build Plugins.Windows.EventMonitor
      run: dotnet build "SP.Core/Plugins/Detection/Windows.Event.Monitor/Plugins.Windows.Event.Monitor.csproj" /t:Restore,Clean,Rebuild /p:Configuration="Release" /p:Platform="Any CPU" /p:SourceRevisionId="${{ github.sha }}"
    - name: Build Plugins.AbuseIP
      run: dotnet build "SP.Core/Plugins/Reporting/AbuseIP/Plugins.AbuseIP.csproj" /t:Restore,Clean,Rebuild /p:Configuration="Release" /p:Platform="Any CPU" /p:SourceRevisionId="${{ github.sha }}"
    - name: Build LiveReport.SignalR
      run: dotnet build "SP.Core/Plugins/Reporting/LiveReport.SignalR/Plugins.LiveReport.SignalR.csproj" /t:Restore,Clean,Rebuild /p:Configuration="Release" /p:Platform="Any CPU" /p:SourceRevisionId="${{ github.sha }}"
#    - name: Build Plugins.Windows.Firewall
#      run: dotnet build "SP.Core/Plugins/System/Windows.Firewall/Plugins.Windows.Firewall.csproj" /t:Restore,Clean,Rebuild /p:Configuration="Release" /p:Platform="Any CPU" /p:SourceRevisionId="${{ github.sha }}"

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.0
      with:
          # Artifact name
            name: Archive build
            # A file, directory or wildcard pattern that describes what to upload
            path: |
              SP.Core/SP.Core/bin/Any CPU/Release/netcoreapp3.1/
              SP.Core/Plugins/**/**/bin/Any CPU/Release/netcoreapp3.1/
            retention-days: 90
